---

- name: deploy bash_prompt.sh for user ${prpt_user.name}
  ansible.builtin.file:
    src: bash_prompt.sh
    dest: "${prpt_user.homedir}/.config/"
    owner: ${prpt_user.name}
    group: ${prpt_user.group}
    mode: '0644'

- name: set bash prompt for user ${prpt_user}
  ansible.builtin.lineinfile:
    path: "${prpt_user.homedir}/.bashrc"
    line: source "${prpt_user.homedir}/.config/bash_prompt.sh"
